app:
  build: .
  command: python3 -u app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
  
db:
  image: mongo:latest
  hostname: mongodb
  
  volumes:
    - /home/user/mongodb/data:/data/db 
  ports:
    - 27017:27017